### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by doubleflying** [Maples7/MsgBoard#3]
我最近也在搭基于NodeJS个人博客，准备部署上线，不知能否加个 Q：842966847

**Comment by Maples7** [comment]
这个Repo只是一个入门的练手Demo，并不能真正线上运行，仅供参考。

**Comment by Maples7** [comment]
而且业务是留言板，不是博客……

**Comment by doubleflying** [comment]
这个 练手的 DEMO 部分功能 还是可以 参考使用的嘛 真正线上部署运行 有啥问题？

**Comment by doubleflying** [comment]
@Maples7 你这个 代码结构 还是可以复用的

**Comment by Maples7** [comment]
没真正在生成环境跑过，你可以试试……
功能相当简单……就是一般的Express项目结构

如果你一定要自己写代码，我建议你参考 [Maples7/weibo](https://github.com/Maples7/weibo) 这个，基本可以达到生成环境的代码要求（代码风格可能不大统一，用户相关部分是另一个人写的，那部分可能比较糙）。如果只是想搭建个个人博客，那建议你用[hexo](https://hexo.io/zh-cn/)，参考这个：[Maples7/blog](https://github.com/Maples7/blog)
